### ISSUE TITLE
Swift 3.0 and xcode 8 support?

### ISSUE THREAD

**Issue by relsirc** [kiavashfaisali/KFSwiftImageLoader#11]
Any plans for Swift 3 and code 8 support?

**Comment by francocorreasosa** [comment]
Same question here.

**Comment by truemetal** [comment]
Looks like this is the answer guys: https://github.com/kiavashfaisali/KFSwiftImageLoader/issues/10

**Comment by kiavashfaisali** [comment]
Hey guys,

I'm going to be pushing the Swift 3.0 update this weekend, be on the lookout Sunday the 25th at the latest!

**Comment by kiavashfaisali** [comment]
I've finished the actual Swift 3.0 migration work in a new "swift_3" branch, but I want to take some extra time to refactor the code and reduce duplication as there is currently a bit of code duplication.

Also, the refactor should open the gates for watchOS 3.0 support, as the Apple Watch example app had only ever worked for watchOS 1.0 since the native compilation of watchOS 2.0+ requires iOS-specific modules to not be imported in watchOS 2.0+ files.

Sorry for the inconvenience, but everything should be good next weekend.

**Comment by kiavashfaisali** [comment]
KFSwiftImageLoader 3.0.0 is now released with Swift 3.0 optimizations and modernization.

Thank you!
