### ISSUE TITLE
Swift 2.0 support

### ISSUE THREAD

**Issue by support3ds** [kiavashfaisali/KFSwiftImageLoader#5]
Since updating to xcode 7 the library has multiple errors.
Are you planing to maintain the library to support Swift 2.0?

**Comment by kiavashfaisali** [comment]
Yes, the update should be out within this week :)
Sorry for the long wait!

**Comment by support3ds** [comment]
Thank you for your prompt reply. ;)

**Comment by kiavashfaisali** [comment]
Unfortunately this is deferred until next weekend, been a busy week for me. Sorry about the inconvenience.

**Comment by mousa-sh** [comment]
would you please update the code which I need it urgently, Thanks for your good job ;)

**Comment by kiavashfaisali** [comment]
Yes, will definitely get around to it this weekend :)

**Comment by mousa-sh** [comment]
مرسی کیاوش ;)

**Comment by kiavashfaisali** [comment]
KFSwiftImageLoader 2.0.0 is now live with Swift 2.0 updates and Xcode 7.0 compatibility. Your code should mostly stay the same, but the one breaking change will be in the fact that errors come back as optionals (NSError?) instead of implicitly-unwrapped optionals (NSError!).

Update your podfile as follows:
pod 'KFSwiftImageLoader', '~> 2.0'

Please let me know if you experience any issues.
Enjoy! :)
